//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.IT.Seci.Idam.Grs.Entities
{
    using System;
    using System.Collections.Generic;
    #pragma warning disable 1591
    public partial class ComputerRole
    {
        public string RoleDescription { get; set; }
        public int ComputerRoleId { get; set; }
    }
}
