//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel.IT.Seci.Idam.Grs.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    #pragma warning disable 1591
    public partial class GRSEntities : DbContext
    {
        public GRSEntities()
            : base("name=GRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ComputerRole> ComputerRoles { get; set; }
    }
}
